# 特征
    1.多维性
    2.同质性（把不同的强制转化到一块）
## 代码示例

In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


属性(常用)：
    shape---形状---arr.shape

    ndim---维数---arr.ndim

    size---总元素个数---arr.size

    dtype---元素属性（同质性）---arr.dtype

## 一.基础ndarray创建（如上）

In [ ]:
import numpy as np

In [2]:
list1=[1,2,3]
list2=[4,5,6]
arr1=np.array(list1)
arr2=np.array(list2)
print(arr1)
print(arr2)
print(f"list1的维数是{arr1.ndim}")#属性
print(f"list2的维数是{arr2.ndim}")

[1 2 3]
[4 5 6]
list1的维数是1
list2的维数是1


In [3]:
arr=np.array(list1,dtype=np.float64)#强制转化数据类型
print(arr)

[1. 2. 3.]


In [4]:
#copy
arr1=np.copy(arr)#arr1与arr元素和原始数组相同，但是不是一个数组了
print(arr1)


[1. 2. 3.]


In [5]:
arr1[0]=8
print(arr1)

[8. 2. 3.]


In [6]:
print(arr)#改新的arr1没有影响旧的arr

[1. 2. 3.]


## 预定义形状

In [1]:
#全0形状
import numpy as np
arr = np.zeros((9,9))
arr1=np.array(arr,dtype=np.int64)
print(arr1)
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
#一维的
import numpy as np
arr=np.zeros((200,),dtype=np.int64)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [3]:
#全1的 和上述类似
import numpy as np
arr=np.ones((200,),dtype=np.int64)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [2]:
#未初始化
import numpy as np
arr=(np.empty((4,5)))#这个值是随机的 并且执行更快
print(arr)

[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [3]:
#填充其他数用full
import numpy as np
arr=np.full((6,6),2025)
print(arr)

[[2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]]


In [13]:
#用零 一 empty 替换
import numpy as np
arr1=np.zeros_like(arr)
arr2=np.empty_like(arr)
arr3=np.full_like(arr,2026)
print(arr1)
print(arr2)
print(arr3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]]
