# 创建
    特征1.多维性
        2.同质性（把不同的强制转化到一块）
 代码示例

In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


属性(常用)：
    shape---形状---arr.shape

    ndim---维数---arr.ndim

    size---总元素个数---arr.size

    dtype---元素属性（同质性）---arr.dtype

## 一.numpy_ndarray_创建

### （一）.基础ndarray创建（如上）

In [5]:
import numpy as np

In [6]:
list1=[1,2,3]
list2=[4,5,6]
arr1=np.array(list1)
arr2=np.array(list2)
print(arr1)
print(arr2)
print(f"list1的维数是{arr1.ndim}")#属性
print(f"list2的维数是{arr2.ndim}")

[1 2 3]
[4 5 6]
list1的维数是1
list2的维数是1


In [7]:
arr=np.array(list1,dtype=np.float64)#强制转化数据类型
print(arr)

[1. 2. 3.]


In [8]:
#copy
arr1=np.copy(arr)#arr1与arr元素和原始数组相同，但是不是一个数组了
print(arr1)


[1. 2. 3.]


In [9]:
arr1[0]=8
print(arr1)

[8. 2. 3.]


In [10]:
print(arr)#改新的arr1没有影响旧的arr

[1. 2. 3.]


### （二）.预定义形状

In [11]:
#全0形状
import numpy as np
arr = np.zeros((9,9))
arr1=np.array(arr,dtype=np.int64)
print(arr1)
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
#一维的
import numpy as np
arr=np.zeros((200,),dtype=np.int64)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [13]:
#全1的 和上述类似
import numpy as np
arr=np.ones((200,),dtype=np.int64)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [14]:
#未初始化
import numpy as np
arr=(np.empty((4,5)))#这个值是随机的 并且执行更快
print(arr)

[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [15]:
#填充其他数用full
import numpy as np
arr=np.full((6,6),2025)
print(arr)

[[2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]
 [2025 2025 2025 2025 2025 2025]]


In [16]:
#用零 一 empty 替换
import numpy as np
arr1=np.zeros_like(arr)
arr2=np.empty_like(arr)
arr3=np.full_like(arr,2026)
print(arr1)
print(arr2)
print(arr3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026]]


### （三）等差数列

In [17]:
import numpy as np
arr=np.arange(8787879,10000000,6)#（开始，结束，步长）
print(arr)

[8787879 8787885 8787891 ... 9999987 9999993 9999999]


In [18]:
#等间隔数列
import numpy as np
app=np.linspace(1,9999,6)#开始，结束，要6个数
print(app)

[1.0000e+00 2.0006e+03 4.0002e+03 5.9998e+03 7.9994e+03 9.9990e+03]


###    (四)对数间隔数列

In [19]:
import numpy as np
arr=np.logspace(0,4,3,base=3)#0到4分成三份0，2，4做指数 底数为3
print(arr)

[ 1.  9. 81.]


In [20]:
import numpy as np
arr=np.logspace(0,4,4,base=3)#0到4分成四份做指数 底数为3
print(arr)

[ 1.          4.32674871 18.72075441 81.        ]


## 二.特殊矩阵生成

### （1）单位矩阵

In [21]:
import numpy as np
arr=np.eye(7)#7为阶数
print(arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### (2)对角矩阵

In [22]:
import numpy as np
arr=np.diag([1,2,3,4,5,6,7,8])
print(arr)


[[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 5 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 8]]


### (3)随机数组生成

In [23]:
#生成（0，1）之间均匀的浮点数
import numpy as np
arr=np.random.rand(3,4)#三行四列
print(arr)

[[0.02836519 0.48257338 0.6531501  0.20008904]
 [0.0789944  0.25816921 0.99141632 0.87767159]
 [0.17683728 0.93731359 0.52188964 0.31983001]]


In [24]:
#生成指定范围内的浮点数
import numpy as np
arr=np.random.uniform(1,10,(4,4))#四行四列 范围从1到10
print(arr)

[[4.31021143 1.26789087 1.40900028 8.63000586]
 [5.08109218 9.82101583 2.34110025 1.89553069]
 [6.10162329 4.00697156 6.88209557 1.81333086]
 [4.2298566  1.64459363 4.27339204 4.73792528]]


In [25]:
#生成随机整数
import numpy as np
arr=np.random.randint(3,1000,(6,6))#从三到一千 6行6列
print(arr)

[[ 33 210 281  69 373 972]
 [802 510 298 915 559 288]
 [181 963 696  96 833 106]
 [383 392 879 981 423 465]
 [507 847 176 850 778 353]
 [334 256 122 397 320 446]]


In [26]:
#生成符合正态分布的随机数列
import numpy as np
arr=np.random.randn(7,7)#shape
print(arr)

[[-1.20749779  0.71927666  0.10095217  0.73336827  0.92301056  1.11827438
   0.56229918]
 [-0.39472365  1.12867416 -1.82324024  0.17946509  0.33152241 -1.39746257
   0.63776142]
 [-0.88842903  3.13956402  0.85326807  2.50842682  0.72822503 -0.24589547
  -0.62776218]
 [-0.9294526   1.23762188  1.16850989  0.15116569  0.82551169 -0.27517859
   2.19740887]
 [ 0.06015868  0.72842497 -0.4634052  -0.13200897  0.34071964  0.51952916
   0.06287235]
 [ 0.40957175 -0.28788466 -0.69122255 -1.85675609 -0.38394243 -0.44854222
   0.57574399]
 [-1.13154699 -1.04899591 -1.0756588  -1.52567516  0.17519802  0.66114618
   0.33025566]]


In [27]:
#种子（把随即生成的数固定下来）（参考我的世界里的种子）
import numpy as np
np.random.seed(7)#尝试多少次都是一样的
arr=np.random.randn(7,7)

print(arr)


[[ 1.69052570e+00 -4.65937371e-01  3.28201637e-02  4.07516283e-01
  -7.88923029e-01  2.06557291e-03 -8.90385858e-04]
 [-1.75472431e+00  1.01765801e+00  6.00498516e-01 -6.25428974e-01
  -1.71548261e-01  5.05299374e-01 -2.61356415e-01]
 [-2.42749079e-01 -1.45324141e+00  5.54580312e-01  1.23880905e-01
   2.74459924e-01 -1.52652453e+00  1.65069969e+00]
 [ 1.54335535e-01 -3.87139943e-01  2.02907222e+00 -4.53860299e-02
  -1.45067870e+00 -4.05227855e-01 -2.28831510e+00]
 [ 1.04939655e+00 -4.16474319e-01 -7.42553525e-01  1.07247013e+00
  -1.65107559e+00  5.35429356e-01 -2.06441480e+00]
 [-6.62159340e-01 -1.20421985e+00  1.46197563e+00  1.76616088e+00
  -3.29413752e-01  8.40733242e-01 -1.79986401e-01]
 [ 5.68061887e-01 -7.52837196e-01 -1.70833920e+00 -1.80309866e+00
   3.83121852e-01  2.24759505e+00  2.69411631e-01]]


# 运算

## 一.索引与切片

(1)基本索引

In [28]:
import numpy as np
arr=np.random.randint(1,100,10)#若10替换成(1,10)就变成了矩阵
print(arr[1])#引用第二个
print(arr[-1])#倒数第一个
print(arr[:])#引用全部
print(arr[2:9])#第三个到第九个（因为左闭右开）
#等价的可以用slice函数
print(arr[slice(2,5)])
print(arr[slice(2,10,2)])#加了个步长
#bool索引（满足条件的被索引）支持逻辑运算符(and& or| not~)
print(arr[arr>10])
print(arr[(arr>10)&(arr<50)])
print(arr[~(arr<50)])

68
5
[77 68 15 21 54 16 60 36 49  5]
[15 21 54 16 60 36 49]
[15 21 54]
[15 54 60 49]
[77 68 15 21 54 16 60 36 49]
[15 21 16 36 49]
[77 68 54 60]


矩阵的索引

In [1]:
import numpy as np
arr=np.random.randint(1,100,(10,10))
print(arr)
print(arr[2])#引用第三行
print(arr[2,2:7])#引用第三行第3个数到第七个数
print(arr[2,6])#第三行第七列
#用slice函数
print(arr[slice(2)])
#bool索引
print(arr[arr>30])
print(arr[3][arr[3]>40])#第四行的bool索引

[[17 35 82 20 33 42  5  8 69 12]
 [78 98 51 64 60 23 41 53  4 77]
 [99 94 40 51 67 66 51 57 55 67]
 [20 21 34 90 93 99 35 86 69 45]
 [29 18 89 47 50 96  9  7 38 69]
 [32 70 58  9 12 21  3 97 25 98]
 [80 36 39 90 72 33 53 44 45 43]
 [18 96 50 24 45 18 44 88 35 16]
 [73 59 37 63 20 48 11 65 58 26]
 [36 80 17 88 43 72 19 59 81 96]]
[99 94 40 51 67 66 51 57 55 67]
[40 51 67 66 51]
51
[[17 35 82 20 33 42  5  8 69 12]
 [78 98 51 64 60 23 41 53  4 77]]
[35 82 33 42 69 78 98 51 64 60 41 53 77 99 94 40 51 67 66 51 57 55 67 34
 90 93 99 35 86 69 45 89 47 50 96 38 69 32 70 58 97 98 80 36 39 90 72 33
 53 44 45 43 96 50 45 44 88 35 73 59 37 63 48 65 58 36 80 88 43 72 59 81
 96]
[90 93 99 86 69 45]


## ndarray运算

1.加法

In [2]:
#算数（对应索引相加）
import numpy as np
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)
print(arr1+arr2)

[[7 2 5]
 [7 3 5]]
[[4 2 1]
 [3 7 4]]
[[11  4  6]
 [10 10  9]]


In [3]:
#广播机制：把（1，n）和（n,1）形状的数组复制成（n,n）运算，其他报错
import numpy as np
arr1=np.random.randint(1,10,(1,5))
arr2=np.random.randint(1,10,(5,1))
print(arr1)
print(arr2)
print(arr1+arr2)

[[3 4 2 3 6]]
[[6]
 [8]
 [7]
 [4]
 [8]]
[[ 9 10  8  9 12]
 [11 12 10 11 14]
 [10 11  9 10 13]
 [ 7  8  6  7 10]
 [11 12 10 11 14]]


2.乘法

In [2]:
s#此为向量乘法
import numpy as np
arr1=np.random.randint(1,10,(1,3))
arr2=np.random.randint(1,10,(3,1))
print(arr1)
print(arr2)
print(arr1@arr2)

[[5 4 4]]
[[9]
 [1]
 [8]]
[[81]]


3.常用函数

基本数学

In [3]:
import numpy as np
p=4
q=9
a1=np.sqrt(p)#平方
a2=np.exp(p)
a3=np.log(p)#以e为底
a4=np.sin(p)
a5=np.power(p,q)#a的b次幂
a6=np.round(q)#向下取整，四舍五入
print(a1,a2,a3,a4,a5,a6)

2.0 54.598150033144236 1.3862943611198906 -0.7568024953079282 262144 9


统计

In [5]:
import numpy as np
x=np.random.randint(1,10,(1,10))
y=np.random.randint(1,10,(1,10))
a1=np.sum(x)#求和
a2=np.mean(y)#平均数
a3=np.median(y)#中位数
a4=np.std(x)#标准差
a5=np.var(x)#方差
a6=np.min(x)
a7=np.max(x)
a8=np.percentile(y,40)#百分之40分位数
print(a1,a2,a3,a4)
print(a5,a6,a7,a8)
print(np.sum(x))
print(np.cumprod(x))#累计乘积，第i个 和前i-1个乘

50 5.6 5.5 2.23606797749979
5.0 2 9 5.0
50
[      7      56     112     560    2240    8960   80640  403200 1612800
 3225600]


比较


In [22]:
import numpy as np
x=0
y=9
a1=np.greater(x,y)#x是否比y大
a2=np.less(x,y)
a3=np.logical_and(x,y)#逻辑运算符
a4=np.logical_or(x,y)
z=np.random.randint(1,10,(1,10))

a5=np.logical_not(z)
a6=np.logical_not(x)
print(a1,a2)
print(z)
print(a3)
print(a4)
print(a6)
print(a5)
print(np.where(z>3,z,0))#符合条件从z里取 不符合变成0
print(np.where(z>3,1,0))#符合条件变成1 不符合变成0




False True
[[1 2 5 8 5 3 1 2 6 5]]
False
True
True
[[False False False False False False False False False False]]
[[0 0 5 8 5 0 0 0 6 5]]
[[0 0 1 1 1 0 0 0 1 1]]


In [2]:
#检测考试是否及格
import numpy as np
score=np.random.randint(30,100,20)
print(score)
print(np.where(score<60,'不及格',np.where(score<80,'良好','优秀')))

[86 37 72 87 71 63 90 81 37 95 53 41 67 76 82 39 46 49 30 44]
['优秀' '不及格' '良好' '优秀' '良好' '良好' '优秀' '优秀' '不及格' '优秀' '不及格' '不及格' '良好' '良好'
 '优秀' '不及格' '不及格' '不及格' '不及格' '不及格']


In [1]:
#np.select条件
import numpy as np
score=np.random.randint(30,100,20)
print(score)
print(np.select([score<60,(score>=60)&(score<=80),score>80],['不及格','良好','优秀'],default='未知'))

[79 48 75 81 98 64 98 52 32 64 33 96 94 74 73 88 85 41 45 96]
['良好' '不及格' '良好' '优秀' '优秀' '良好' '优秀' '不及格' '不及格' '良好' '不及格' '优秀' '优秀' '良好'
 '良好' '优秀' '优秀' '不及格' '不及格' '优秀']


排序

In [5]:
import numpy as np
np.random.seed(125)
arr=np.random.randint(1,300,30)
print(arr)
#arr.sort()
#print(arr)这样会改原始数据 污染了原始数据 但是下边的就不会 见下
print(np.sort(arr))
print(np.argsort(arr))#排序后的索引
print(arr)

[158 227 256 111 206  65 294  87 227 224 156 182 187 257 252  51  93 266
 127 246 132  77  48 264 285 298  82 133 197 292]
[ 48  51  65  77  82  87  93 111 127 132 133 156 158 182 187 197 206 224
 227 227 246 252 256 257 264 266 285 292 294 298]
[22 15  5 21 26  7 16  3 18 20 27 10  0 11 12 28  4  9  8  1 19 14  2 13
 23 17 24 29  6 25]
[158 227 256 111 206  65 294  87 227 224 156 182 187 257 252  51  93 266
 127 246 132  77  48 264 285 298  82 133 197 292]


去重

In [6]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,60,30)
print(arr)
print(np.unique(arr))

[12 28  7 50  3  4  4 13 49 23 50 53  6 14 26 35 12 55 11  1 54 41 13 14
 19 26 36 37 36 34]
[ 1  3  4  6  7 11 12 13 14 19 23 26 28 34 35 36 37 41 49 50 53 54 55]


数组拼接

In [8]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2)))


[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


数组的分割

In [1]:
import numpy as np
np.random.seed(13)
arr=np.random.randint(1,300,30)
print(arr)
print(np.split(arr,5))#分成五份
print(np.split(arr,6))#注意必须能等分

[177  75  17 231 245 154 237 245 127 230  75 259 161 150 140  76   2 147
 281  12 297  23 291 181 121 180 214  25 256 114]
[array([177,  75,  17, 231, 245, 154], dtype=int32), array([237, 245, 127, 230,  75, 259], dtype=int32), array([161, 150, 140,  76,   2, 147], dtype=int32), array([281,  12, 297,  23, 291, 181], dtype=int32), array([121, 180, 214,  25, 256, 114], dtype=int32)]
[array([177,  75,  17, 231, 245], dtype=int32), array([154, 237, 245, 127, 230], dtype=int32), array([ 75, 259, 161, 150, 140], dtype=int32), array([ 76,   2, 147, 281,  12], dtype=int32), array([297,  23, 291, 181, 121], dtype=int32), array([180, 214,  25, 256, 114], dtype=int32)]


调整数组形状

In [2]:
print(np.reshape(arr,(3,10)))#arr为上述‘数组分割’生成的随机数

[[177  75  17 231 245 154 237 245 127 230]
 [ 75 259 161 150 140  76   2 147 281  12]
 [297  23 291 181 121 180 214  25 256 114]]


# 练习与实践